### ISSUE TITLE
deamon-mode: NameError: name 'Notify' is not defined

### ISSUE THREAD

**Issue by r00t-** [schorschii/ImagingEdge4Linux#1]
daemon-mode dies with
```
    self.notification = Notify.Notification.new('ImagingEdge4Linux', 'Sync running...')
NameError: name 'Notify' is not defined
```
looks like something about the code that makes desktop notifications optional is broken in that case.

**Comment by schorschii** [comment]
Thanks, it should work now even if the Notify module is not available.
