### ISSUE TITLE
GLib dependency installation

### ISSUE THREAD

**Issue by jasalt** [schorschii/ImagingEdge4Linux#3]
Looks like a great project. I was testing this shortly (on Debian) and noted that the GLib needs to be installed before the script would run properly, giving:

```
  File "/home/user/dev/ImagingEdge4Linux/imaging-edge.py", line 5, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
```

Maybe related packages could be included in `requirements.txt` and/or as extra pre-install instructions if it depends on packages from elsewhere. I quickly tried `pip install GLib` but that didn't get any further.

**Comment by schorschii** [comment]
Thanks for the info. I thought the "gi" module is a core package pre-installed on most distros. It must be installed through your distro's package manager, there is no package for that in PyPI. I added an installation note for that to the README.md and also a fallback if the module is not available.

Can you please test both? If the "gi" module is not installed, the script now always uses the English folder name "~/Pictures". Then, please install `python3-gi` and it should use your localized folder name and the warning "no GLib module available" should be gone.

**Comment by schorschii** [comment]
@jasalt were you able to test it?

**Comment by jasalt** [comment]
@schorschii I'll check it this weekend, thank's for help.

**Comment by jasalt** [comment]
I got it working and it seems mainly issue with `pyenv` not finding the globally installed `python3-gi` package. Managed to get the script working with `/usr/bin/python3 imaging-edge.py`.

**Comment by jasalt** [comment]
Much better this way to not crash if GLib module is not available. Resolving the user Pictures directory is nice, but a command line option or environment variable for setting path would be useful, and a config file maybe later on. Personally would maybe default downloading pictures to current working directory, but maybe that's a matter of taste also.

**Comment by schorschii** [comment]
For running in venvs, use the parameter `--system-site-packages` when creating the venv to also include the system-wide Python modules.
```
python3 -m venv --system-site-packages venv
```

A command line option for setting the directory manually already exists: `--output-dir`
