### ISSUE TITLE
RAW image support

### ISSUE THREAD

**Issue by jasalt** [schorschii/ImagingEdge4Linux#4]
Downloading `.ARW` (Sony RAW format) doesn't seem to be supported. Gives `Unable to find a download candidate!`. Videos in `.MP4` format seem to download fine however.

**Comment by schorschii** [comment]
The script now downloads the best JPEG preview available for RAW images. The API unfortunately does not allow to download the original .ARW file.

**Comment by jasalt** [comment]
I didn't realize this even, but indeed, the official mobile app doesn't transfer RAWs either but converts them on the fly.
The same behavior is good here also.

I think I had some success getting RAW's out over USB cable with http://gphoto.org/ related tools some time on Linux, but I guess it is more for tethering use case, not media transfers of already taken images.
