### ISSUE TITLE
Connect to camera wifi network and connect back after transfer

### ISSUE THREAD

**Issue by jasalt** [schorschii/ImagingEdge4Linux#5]
With laptop connected to wireless network, it would be nice that script would connect to camera wifi, and then connect back to previously used wifi connection. Simple example bash wrapper script `get_images.sh` that works for me on MX Linux KDE (Debian):

```
#!/bin/bash

# Backup current network connection details
CURRENT_SSID=$(nmcli -t c show --active |grep "wlan0"| head -n 1 | cut -d ':' -f 1)

SSID="DIRECT-3XXX:DSC-RX100M7"
PASSWORD="z1zXXXXX"

# Connect to the specified SSID with the given password
nmcli dev wifi connect "$SSID" password "$PASSWORD"

# Wait for a few seconds to ensure the connection is established
sleep 6

python3 imaging-edge.py

if [ -n "$CURRENT_SSID" ]; then
	echo "Reconnecting to the previously connected network..."
	nmcli con up "$CURRENT_SSID"
else
	echo "No previously connected network found."
	exit 1
fi

echo "Done."
```

Usage: place in same dir as `imaging-edge.py`, edit camera wifi credentials, run `chmod +x get_images.sh` and `./get_images.sh`. 

If this functionality is convenient to include in Python script, either by using some network manager library or using shell commands, it could be utilized when calling the script with eg. `imaging-edge.py --ssid=<camera-ssid> --password=<camera-wifi-password>` and maybe a flag `--reconnect` that would attempt to connect back to previous wifi network.

**Comment by schorschii** [comment]
Thanks for this idea. I added your shell script to the repo.
